/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TeachersTeacherIdRouteImport } from './routes/teachers.$teacherId'
import { Route as StagesLevelRouteImport } from './routes/stages.$level'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLecturesRouteImport } from './routes/_authenticated/lectures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedStaffSupportRouteImport } from './routes/_authenticated/staff.support'
import { Route as AuthenticatedStaffStudentsRouteImport } from './routes/_authenticated/staff.students'
import { Route as AuthenticatedStaffMontageRouteImport } from './routes/_authenticated/staff.montage'
import { Route as AuthenticatedManageCourseIdRouteImport } from './routes/_authenticated/manage.$courseId'
import { Route as AuthenticatedLearnCourseIdRouteImport } from './routes/_authenticated/learn.$courseId'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin.teachers'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminStagesRouteImport } from './routes/_authenticated/admin.stages'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated/admin.knowledge'
import { Route as AuthenticatedAdminEarningsRouteImport } from './routes/_authenticated/admin.earnings'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated/admin.devices'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin.accounts'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdRoute = TeachersTeacherIdRouteImport.update({
  id: '/teachers/$teacherId',
  path: '/teachers/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesLevelRoute = StagesLevelRouteImport.update({
  id: '/stages/$level',
  path: '/stages/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLecturesRoute = AuthenticatedLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStaffSupportRoute =
  AuthenticatedStaffSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffStudentsRoute =
  AuthenticatedStaffStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffMontageRoute =
  AuthenticatedStaffMontageRouteImport.update({
    id: '/montage',
    path: '/montage',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedManageCourseIdRoute =
  AuthenticatedManageCourseIdRouteImport.update({
    id: '/manage/$courseId',
    path: '/manage/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnCourseIdRoute =
  AuthenticatedLearnCourseIdRouteImport.update({
    id: '/learn/$courseId',
    path: '/learn/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStagesRoute =
  AuthenticatedAdminStagesRouteImport.update({
    id: '/stages',
    path: '/stages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEarningsRoute =
  AuthenticatedAdminEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lectures': typeof AuthenticatedLecturesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/stages/$level': typeof StagesLevelRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/manage/$courseId': typeof AuthenticatedManageCourseIdRoute
  '/staff/montage': typeof AuthenticatedStaffMontageRoute
  '/staff/students': typeof AuthenticatedStaffStudentsRoute
  '/staff/support': typeof AuthenticatedStaffSupportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/ai': typeof AuthenticatedAiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lectures': typeof AuthenticatedLecturesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/stages/$level': typeof StagesLevelRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/manage/$courseId': typeof AuthenticatedManageCourseIdRoute
  '/staff/montage': typeof AuthenticatedStaffMontageRoute
  '/staff/students': typeof AuthenticatedStaffStudentsRoute
  '/staff/support': typeof AuthenticatedStaffSupportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lectures': typeof AuthenticatedLecturesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/stages/$level': typeof StagesLevelRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/stages': typeof AuthenticatedAdminStagesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
  '/_authenticated/manage/$courseId': typeof AuthenticatedManageCourseIdRoute
  '/_authenticated/staff/montage': typeof AuthenticatedStaffMontageRoute
  '/_authenticated/staff/students': typeof AuthenticatedStaffStudentsRoute
  '/_authenticated/staff/support': typeof AuthenticatedStaffSupportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/support'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/lectures'
    | '/onboarding'
    | '/profile'
    | '/staff'
    | '/teacher'
    | '/courses/$courseId'
    | '/stages/$level'
    | '/teachers/$teacherId'
    | '/courses/'
    | '/admin/accounts'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/devices'
    | '/admin/earnings'
    | '/admin/knowledge'
    | '/admin/payments'
    | '/admin/stages'
    | '/admin/subscriptions'
    | '/admin/teachers'
    | '/learn/$courseId'
    | '/manage/$courseId'
    | '/staff/montage'
    | '/staff/students'
    | '/staff/support'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/support'
    | '/ai'
    | '/dashboard'
    | '/lectures'
    | '/onboarding'
    | '/profile'
    | '/teacher'
    | '/courses/$courseId'
    | '/stages/$level'
    | '/teachers/$teacherId'
    | '/courses'
    | '/admin/accounts'
    | '/admin/coupons'
    | '/admin/courses'
    | '/admin/devices'
    | '/admin/earnings'
    | '/admin/knowledge'
    | '/admin/payments'
    | '/admin/stages'
    | '/admin/subscriptions'
    | '/admin/teachers'
    | '/learn/$courseId'
    | '/manage/$courseId'
    | '/staff/montage'
    | '/staff/students'
    | '/staff/support'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/support'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/lectures'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/staff'
    | '/_authenticated/teacher'
    | '/courses/$courseId'
    | '/stages/$level'
    | '/teachers/$teacherId'
    | '/courses/'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/earnings'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/stages'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/learn/$courseId'
    | '/_authenticated/manage/$courseId'
    | '/_authenticated/staff/montage'
    | '/_authenticated/staff/students'
    | '/_authenticated/staff/support'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  StagesLevelRoute: typeof StagesLevelRoute
  TeachersTeacherIdRoute: typeof TeachersTeacherIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId': {
      id: '/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof TeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$level': {
      id: '/stages/$level'
      path: '/stages/$level'
      fullPath: '/stages/$level'
      preLoaderRoute: typeof StagesLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lectures': {
      id: '/_authenticated/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof AuthenticatedLecturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/staff/support': {
      id: '/_authenticated/staff/support'
      path: '/support'
      fullPath: '/staff/support'
      preLoaderRoute: typeof AuthenticatedStaffSupportRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/students': {
      id: '/_authenticated/staff/students'
      path: '/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof AuthenticatedStaffStudentsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/montage': {
      id: '/_authenticated/staff/montage'
      path: '/montage'
      fullPath: '/staff/montage'
      preLoaderRoute: typeof AuthenticatedStaffMontageRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/manage/$courseId': {
      id: '/_authenticated/manage/$courseId'
      path: '/manage/$courseId'
      fullPath: '/manage/$courseId'
      preLoaderRoute: typeof AuthenticatedManageCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseId': {
      id: '/_authenticated/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stages': {
      id: '/_authenticated/admin/stages'
      path: '/stages'
      fullPath: '/admin/stages'
      preLoaderRoute: typeof AuthenticatedAdminStagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/earnings': {
      id: '/_authenticated/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AuthenticatedAdminEarningsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminEarningsRoute: typeof AuthenticatedAdminEarningsRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminStagesRoute: typeof AuthenticatedAdminStagesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminEarningsRoute: AuthenticatedAdminEarningsRoute,
  AuthenticatedAdminKnowledgeRoute: AuthenticatedAdminKnowledgeRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminStagesRoute: AuthenticatedAdminStagesRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffMontageRoute: typeof AuthenticatedStaffMontageRoute
  AuthenticatedStaffStudentsRoute: typeof AuthenticatedStaffStudentsRoute
  AuthenticatedStaffSupportRoute: typeof AuthenticatedStaffSupportRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffMontageRoute: AuthenticatedStaffMontageRoute,
  AuthenticatedStaffStudentsRoute: AuthenticatedStaffStudentsRoute,
  AuthenticatedStaffSupportRoute: AuthenticatedStaffSupportRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLecturesRoute: typeof AuthenticatedLecturesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedLearnCourseIdRoute: typeof AuthenticatedLearnCourseIdRoute
  AuthenticatedManageCourseIdRoute: typeof AuthenticatedManageCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLecturesRoute: AuthenticatedLecturesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedLearnCourseIdRoute: AuthenticatedLearnCourseIdRoute,
  AuthenticatedManageCourseIdRoute: AuthenticatedManageCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  StagesLevelRoute: StagesLevelRoute,
  TeachersTeacherIdRoute: TeachersTeacherIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
